services:
  - type: web
    name: zga-geek-arena
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
    plan: free
    region: frankfurt
